# Generated by Django 3.2.9 on 2021-11-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_extendeduser_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
