# Generated by Django 3.2.9 on 2022-01-24 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20220123_2121'),
        ('infraction_types', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infractiontype',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='devices.device'),
        ),
    ]
