# Generated by Django 3.2.9 on 2022-02-24 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220221_2243'),
        ('infraction_types', '0002_infractiontype_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infractiontype',
            name='device',
        ),
        migrations.AddField(
            model_name='infractiontype',
            name='account',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infraction_types', to='accounts.account'),
        ),
    ]
