# Generated by Django 3.2.9 on 2022-02-19 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infraction_types', '0002_infractiontype_device'),
        ('infraction_events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infractionevent',
            name='account',
        ),
        migrations.AddField(
            model_name='infractionevent',
            name='infraction_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='infraction_types.infractiontype'),
        ),
    ]
