# Generated by Django 3.2.9 on 2022-02-24 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('infraction_types', '0002_infractiontype_device'),
        ('infraction_events', '0002_auto_20220219_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='infractionevent',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infraction_events', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='infractionevent',
            name='infraction_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infraction_events', to='infraction_types.infractiontype'),
        ),
    ]
