version: "3.9"

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'safety-vision-platform-db'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - db:/var/lib/mysql
  web:
    image: safety-vision-platform_web-local
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - app:/code
    ports:
      - "80:8000"
    depends_on:
      - db
volumes:
  db:
  app: