# Generated by Django 3.2.9 on 2022-01-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='stream_name',
            new_name='stream_arn',
        ),
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(default='', max_length=1000, unique=True),
        ),
    ]
