# Generated by Django 3.2.9 on 2022-02-19 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '__first__'),
        ('devices', '0002_auto_20220123_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='device',
            name='stream_arn',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
